[package]
name = "omerbn-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
glob = "0.3.1"
indexmap = "2.3.0"
lazy_static = "1.5.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.48"

[[bin]]
name = "omerbn-rust"
path = "main.rs"
